name: "Elaborate package check"
description: "Thouroughly check an R package on different topics"
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  path:
    description: >
      Which path must be checked. This path is relative to the root of the repository.
    default: "."
  CODECOV_TOKEN:
    description: >
      A token for https://codecov.io.
    default: ""
  aptget:
    description: >
      A list of apt-get packages to install. They should be space separated.
    default: ""

runs:
  using: 'docker'
  image: docker://inbobmk/checklist:dev-token
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.path }}
    - ${{ inputs.CODECOV_TOKEN }}
    - ${{ inputs.aptget }}
